version: "3.8"
services:
  svelte-app:
    build:
      context: ./svelte-app
      dockerfile: Dockerfile
      target: local
    ports:
      - "3000:3000"
    volumes:
      - ./svelte-app/src:/app/src
      - ./svelte-app/static:/app/static
    depends_on:
      - api-service

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
      target: local
    environment:
      - OAUTH_CLIENT_ID=social-client
      - OAUTH_CLIENT_SECRET=social_secret
      - OAUTH_REDIRECT_URI=http://localhost:3000/callback
      - OAUTH_AUTH_URL=http://localhost:8080/realms/social/protocol/openid-connect/auth
      - OAUTH_TOKEN_URL=http://localhost:8080/realms/social/protocol/openid-connect/token
      - JWKS_URL=http://localhost:8080/realms/social/protocol/openid-connect/certs
      - ALLOWED_ORIGIN=http://localhost:3000
      - PORT=4000
      - DATABASE_URL=postgresql://user:password@postgres:5432/social
      - GIN_MODE=debug
    ports:
      - "4000:4000"
    volumes:
      - ./api-service:/app
    depends_on:
      - keycloak
      - postgres
    networks:
      - app-network
    extra_hosts:
      - "localhost:host-gateway"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/local:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    command:
      - start-dev
      - --import-realm
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
  redis_data:
