/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-dark': 'var(--primary-dark)',
        'primary-light': 'var(--primary-light)',
        secondary: 'var(--secondary)',
        background: 'var(--background)',
        surface: 'var(--surface)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        border: 'var(--border)',
        'sidebar-hover': 'var(--sidebar-hover)',
        'sidebar-active': 'var(--sidebar-active)',
        error: 'var(--error)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        hover: 'var(--hover)',
        active: 'var(--active)',
        divider: 'var(--divider)',
        'card-background': 'var(--card-background)',
        'input-background': 'var(--input-background)',
        'input-border': 'var(--input-border)',
        'input-text': 'var(--input-text)',
        'input-placeholder': 'var(--input-placeholder)',
        'button-text': 'var(--button-text)',
        'button-disabled': 'var(--button-disabled)',
        shadow: 'var(--shadow)',
      },
    },
  },
  darkMode: 'class',
  plugins: [],
};
